### ISSUE TITLE
Use directory as project

### ISSUE THREAD

**Issue by SimonBaeumer** [SimonBaeumer/monorepo-operator#28]
It should be possible to configure a directory which will be scanned and synced automatically instead of using a hard-coded file.

Example:

```
directories:
  - dir: projects/
    git-url: git@github.com/SimonBaeumer
    name: ${name}
```
