### ISSUE TITLE
Add ignore-dir 

### ISSUE THREAD

**Issue by SimonBaeumer** [SimonBaeumer/monorepo-operator#34]
I would like to ignore directories if a dir is scanned for projects

It should fali if `ignore-dirs` are defined and `is-dir` is `false`

Example:

```
projects:
- name: {{.DirName}}
  git-url: git@github.com/UserName/{{.DirName}}.git
  path: projects
  is-dir: true
  ignore-dirs:
   - examples
```
